config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'profile', to: 'pages#profile'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events, only: %i[show new create edit update] do
    member do
      get :photos
    end
    resources :albums, only: %i[new create]
    resources :invitations, except: :destroy
    resources :spendings, only: %i[new create index]
    resources :budgets, only: %i[new create edit update]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :spendings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :invitations
  has_many :users, through: :invitations
  has_many :albums
  has_one_attached :photo
  has_one :budget, dependent: :destroy
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save!
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
    # @invitation = current_user.invitations.find_by(event: @event)
    @invitation = current_user.invitations.find_by(event: @event)
    @marker =
      {
        lat: @event.latitude,
        lng: @event.longitude
      }
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def photos
    @event = Event.find(params[:id])
    @albums = @event.albums
  end

  private

  def event_params
    params.require(:event).permit(:start_date, :end_date, :category, :description, :address, :title, :photo)
  end
end

app/views/events/_form.html.erb
<div class= "background">
<br>
  <div class="form-container">
  <h2 class="title">Créer un événement</h2>
    <%= simple_form_for(event) do |f| %>
        <%= f.input :title, label: "Nom de l'événement" %>
        <%= f.input :category, label: "Catégorie de l'événement", collection: ["Anniversaire", "Mariage", "Baptême", "Fête", "Autre"] %>
        <%= f.input :address, label: "Adresse",
                    input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
                    %>
        <%= f.input :start_date, label: "Sélectionnez la date et l'heure de début de votre événement", as: :string, input_html: { class: "range_start"} %>
        <%= f.input :end_date, label: "Sélectionnez la date et l'heure de fin de votre événement", as: :string, input_html: { class: "range_end"} %>
        <%= f.input :description, label: "Description" %>
        <%= f.input :photo, as: :file, label: "Image" %>
        <div class="button-centered"><input type="submit" name="commit" value="Créer votre événement" class="primary-orange-button" data-disable-with="Create Event"></div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div>
    <h1>Modifiez votre événement</h1>
    <%= render "form", event: @event %>
  </div>
</div>

app/views/events/new.html.erb
<%= render "form", event: @event %>

app/views/events/photos.html.erb
<div class="container">
  <div class="title-album"><h1>Album "<%= @event.title %>"</h1>
  <%= link_to "Retourner à l'événement", event_path(@event), class:"primary-orange-button" %></div>
  <div class="row">
    <div class="two-columns">
      <% @albums.each do |album| %>
        <% album.photos.each_with_index do |photo, index| %>
            <%= cl_image_tag photo.key %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <% if @event.photo.attached? %>
    <%= cl_image_tag @event.photo.key, width: 1305, height: 345, crop: :fill, class: "banner" %>
    <% else %>
    <h1>penser à rajouter une image par défaut</h1>
  <% end %>
  <div class="wrapper">
    <div class="left-container">
      <h5 class="--black-big"><%= @event.start_date.strftime("Le %d/%m/%Y à %H:%M") %></h5>
      <h1><%= @event.title %></h1>
      <div class="info-container">
        <div class="d-flex align-items-center">
          <div>
            <i class="fa-solid fa-clock landing-icon icon-size"></i>
          </div>
          <div class="text-icon">
            <h5 class="--black">Date & Heure</h5>
            <p><%= @event.start_date.strftime("Le %d/%m/%Y à %H:%M") %></p>
          </div>
        </div>
        <div class="line"></div>
        <div class="d-flex align-items-center">
          <div>
            <i class="fa-solid fa-compass landing-icon icon-size"></i>
          </div>
          <div class="text-icon">
            <h5 class="--black">Lieu</h5>
            <p><%= @event.address %></p>
          </div>
        </div>
      </div>
      <div class= "style"
      data-controller="map"
      data-map-marker-value="<%= @marker.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>

      <% if @event.budget.present?%>
      <h2>Finances</h2>
      <div class="finance-div">
        <div class="budget-side">
          <div class="d-flex">
          <div>
            <i class="fa-solid fa-coins landing-icon icon-size"></i>
          </div>
          <div class="text-icon">
            <h5 class="--black">Budget total : <%= @event.budget.initial_budget %>€</h5>
            <%= link_to "Mettre à jour mon budget", edit_event_budget_path(@event), class:"primary-orange-button" %>
          </div>
        </div>
        <% else %>
          <div class="finance-div">
          <div class="budget-side d-none">
              <h5></h5>
            <br>
            <br>
        <% end %>
        </div>
        <% if @event.spendings.present? %>
        <div class="chart" data-controller= "collapse-spending">
          <div class="d-flex">
            <% if @event.budget.present?%>
              <div class="d-flex">
                <div>
                  <i class="fa-solid fa-wallet landing-icon icon-size"></i>
                </div>
                <div class="text-icon flex-column">
                  <div class="d-flex">
                    <h5 class="--black">Budget restant : <%= @event.budget.remaining_budget %>€</h5>
                    <button type="button" class="collapsible" data-action="click->collapse-spending#displayList" ><i class="fa-solid fa-caret-right arrow" data-collapse-spending-target="arrow"></i></button>
                  </div>
                  <div class="content" data-collapse-spending-target="list">
                    <ul class="list-group">
                      <% @event.spendings.each do |spending| %>
                      <li class="list-group-item">
                        <strong> <%= spending.category %> </strong>
                        </br>
                        <%= spending.amount %>€
                        <%= @event.start_date.strftime("le %d/%m/%Y") %>
                      </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <% else %>
        <div class="chart d-none" data-controller= "collapse-spending">
          <div class="d-flex">
          </div>
        </div>
        <% end %>
      </div>
      <h2>À propos de cet événement</h2>
      <p><%= @event.description %></p>

      <% if @event.albums.present? %>
        <h2>Album de l'événement</h2>
        <div class="album-section">
          <% @event.albums.each do |album| %>
            <% album.photos.limit(3).each do |photo| %>
            <% if photo %>
              <%= cl_image_tag photo.key %>
            <% end %>
            <% end %>
          <% end %>
        </div>
      <% else %>

      <% end %>
    </div>
   <div class="right-container">
      <div class="gestion-card">
        <h2>Gestion de </br> l'événement</h2>
        <p>Général</p>
        <%= link_to "Modifier l'événement", edit_event_path(@event.id), class:"large-light-orange-button" %>
        <%= link_to "Envoyer des invitations", new_event_invitation_path(@event), class:"large-orange-button" %>
        <%= link_to "Voir mes invités", event_invitations_path(@event), class:"large-grey-button" %>

        <p>Finances</p>
        <% if @event.budget.present? %>
          <%= link_to "Ajouter une dépense", new_event_spending_path(@event), class:"large-orange-button" %>
        <% else %>
          <%= link_to "Ajouter un budget", new_event_budget_path(@event), class:"large-orange-button" %>
        <% end %>
        <p>Album</p>
        <% if @event.albums.present? %>
          <%= link_to "Ajouter une photo", new_event_album_path(@event.id), class:"large-orange-button" %>
          <%= link_to "Voir l'album", photos_event_path(@event.id), class:"large-grey-button" %>
        <% else %>
          <%= link_to "Créer un album", new_event_album_path(@event.id), class:"large-orange-button" %>
        <% end %>
        <p>Cagnotte</p>
        <%= link_to "Participer à la cagnotte", new_event_album_path(@event.id), class:"large-orange-button" %>
      </div>
    </div>

  </div>
</div>

<% if @invitation %>
  <%= simple_form_for [@event, @invitation] do |f|%>
  <%= f.input :status, label: 'Je participe' %>
  <%= f.submit %>
  <% end %>
  <% end %>