config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'profile', to: 'pages#profile'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events, only: %i[show new create edit update] do
    member do
      get :photos
    end
    resources :albums, only: %i[new create]
    resources :invitations, except: :destroy
    resources :spendings, only: %i[new create index]
    resources :budgets, only: %i[new create edit update]
  end
end

app/views/pages/home.html.erb
<div class="container">
    <div class="first-div-landing">
      <div class="first-div-text">
        <h1>Organisez votre événement en toute simplicité.</h1>
        <p>Avec Dionysos, rassemblez toutes les fonctionnalités nécessaires  à l’organisation
        de votre événement dans une seule interface !</p>
        <%= link_to "Créez votre événement", new_event_path, class:"primary-orange-button" %>
      </div>
      <div class="first-div-images d-flex">
        <div class="align-items-center homepage-container-image-banner">
          <img class="seconde-image" src="https://images.unsplash.com/photo-1513546493312-0066d7de3fd2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=740&q=80" alt="">
          <img class="seconde-image" src="https://res.cloudinary.com/dct6y4tya/image/upload/v1670499575/pexels-photo-931162_qjralh.jpg" alt="">
        </div>
        <div class="img-solo d-flex align-items-center">
          <img class="premiere-image" src="https://res.cloudinary.com/dct6y4tya/image/upload/v1670509134/IMG_1589_kh7lqs.jpg" alt="">
        </div>
      </div>
    </div>
  </div>
  <div class="second-div-landing">
    <div>
      <h3 class="h3-size">Dionysos vous facilite la gestion de vos festivités</h3>
      <div class="list-avantages">
        <div class="avantage">
          <h3 class="--number">1.</h3>
          <h5>Rassemblez</h5>
          <p>Les outils utiles à l'organisation de vos événements </p>
        </div>
        <div class="avantage">
          <h3 class="--number">2.</h3>
          <h5>Communiquez</h5>
          <p>Efficacement avec vos invités : invitations, relances, etc...</p>
        </div>
        <div class="avantage">
          <h3 class="--number">3.</h3>
          <h5>Gérez</h5>
          <p>Votre budget et vos dépenses pour ne rien laisser au hasard</p>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="third-div-landing justify-content-between">
      <div class="third-div-landing-img">
        <img src="https://res.cloudinary.com/dct6y4tya/image/upload/v1669977132/Group_25_ihpdkm.png" alt="">
      </div>
      <div class="third-div-landing-text d-flex">
        <div>
          <h1>Comment ça </br> marche ?</h1>
        </div>
        <div class="d-flex">
          <div>
            <i class="fa-solid fa-right-to-bracket landing-icon icon-size"></i>
          </div>
          <div class="text-icon">
            <h5 class="--black">Inscrivez vous</h5>
            <p>Créer votre compte, participer aux événements de vos proches et créer votre propre événement</p>
          </div>
        </div>

        <div class="d-flex">
          <div>
            <i class="fa-solid fa-circle-plus landing-icon icon-size"></i>
          </div>
          <div class="text-icon">
            <h5 class="--black">Créez votre premier événement</h5>
            <p>Enregistrez votre événement et accédez à votre tableau de bord</p>
          </div>
        </div>
        <div class="d-flex">
          <div>
            <i class="fa-solid fa-envelope landing-icon icon-size"></i>
          </div>
          <div class="text-icon">
            <h5 class="--black">Invitez vos proches</h5>
            <p>Envoyez des invitations à vos amis et votre famille par email ou SMS</p>
          </div>
        </div>
        <div class="d-flex">
          <div>
            <i class="fa-solid fa-bars-progress landing-icon icon-size"></i>
          </div>
          <div class="text-icon">
            <h5 class="--black">Gérez votre événement</h5>
            <p>Gérez votre budget, l’album photo de votre événement et vos invités en quelques clics</p>
          </div>
        </div>
      </div>
    </div>

    <div>
      <h1 class="last-title-landing">Une infinité de </br> possibilités</h1>
    </div>

    <div class="fourth-div-landing-img">
      <div class="container-img-landing">
        <img src="https://res.cloudinary.com/dct6y4tya/image/upload/v1670493277/1_iesvtd.jpg" alt="">
        <h4 class="landing-text-img">Mariage</h4>
      </div>
      <div class="container-img-landing">
        <img src="https://res.cloudinary.com/dct6y4tya/image/upload/v1670493277/cake_gky5jp.jpg" alt="">
        <h4 class="landing-text-img">Anniversaire</h4>
      </div>
      <div class="container-img-landing">
        <img src="https://res.cloudinary.com/dct6y4tya/image/upload/v1670494780/sparkle_egiapt.jpg" alt="">
        <h4 class="landing-text-img">Célébration</h4>
      </div>
      <div class="container-img-landing">
        <img src="https://res.cloudinary.com/dct6y4tya/image/upload/v1670493277/holidays_er2fpm.jpg" alt="">
        <h4 class="landing-text-img">Vacances</h4>
      </div>
    </div>

    <div class="last-button-landing">
      <%= link_to "Créez votre événement", new_event_path, class:"primary-orange-button button-bottom-landing" %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <div class="d-flex justify-content-between mt-5 align-items-end mb-3">
    <div>
      <h2>Mes événements</h2>
      <div class= "search-bar"><%= form_with url: profile_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "search-input",
      placeholder: "Rechercher un événement"%>
      <button class="main-btn" type="submit">
      <i class="fa-solid fa-magnifying-glass"></i>
      </button>
      <% end %>
    </div>
  </div>
    <div class="d-flex align-items-center"><%= link_to "Créer un événement", new_event_path, class:"primary-orange-button" %>
    </div>
  </div>
  <table class="w-100">
    <thead>
      <tr class="column-names">
        <th scope="col" class= "border-event-left"><span class="table-titles">Evénements</span></th>
        <th scope="col" class="text-center">Invités</th>
        <th scope="col" class="text-center">Budget</th>
        <th scope="col" class="border-event-right text-center">Statut</th>
      </tr>
    </thead>
    <tbody class="event-content-profile">
      <% @events.each do |event| %>
      <tr class= "row-border">
        <td scope="row" class="d-flex row-table m-3">
          <div>
            <% if event.photo.attached? %>
              <%= cl_image_tag event.photo.key, width: 125, height: 125, crop: :fill, radius: 8 %>
            <% else %>
            <% end %>
          </div>
          <div class="text-event">
            <div class="table-event-name pl-2">
              <h5 class="event-title mt-3"><%= event.title %></h5>
              <p class="event-date"><%= event.start_date.strftime("%d" + "." + "%m" + "." +"%Y") %></p>
            </div>
            <div>
              <%= link_to event_path(event) do %>
                <i class="fa-solid fa-eye icone-event"></i>
              <% end %>
            </div>
          </div>
        </td>
        <td class="text-center">
          <% if event.invitations.present? %>
            <%= event.invitations.length %>
          <% else %>
            <%= "-" %>
          <% end %>
        </td>
        <td class="text-center">
          <% if event.budget.present?%>
            <%= event.budget.initial_budget %>€
          <% else %>
            <%= "-" %>
          <% end %>
        </td>
        <td class="text-center">
          <% if DateTime.now >= event.start_date %>
            <%= "Passé" %>
          <% else %>
            <%= "A venir" %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <h2 class="mt-5">Invitations reçues</h2>
    <div class= "search-bar mb-3"><%= form_with url: profile_path, method: :get do %>
    <%= text_field_tag :query,
    params[:query],
    class: "search-input",
    placeholder: "Rechercher un événement"%>
    <button class="main-btn" type="submit">
    <i class="fa-solid fa-magnifying-glass"></i>
    </button>
    <% end %>
  </div>
  <table class="w-100 mb-5">
    <thead>
      <tr class="column-names">
        <th scope="col" class= "border-event-left"><span class="table-titles">Evénements</span></th>
        <th scope="col" class="text-center">Invités</th>
        <th scope="col" class="border-event-right text-center">Statut</th>
      </tr>
    </thead>
    <tbody class="event-content-profile">
      <% @invitations.each do |invitation| %>
        <tr class= "row-border">
          <td scope="row" class="d-flex row-table m-3">
            <div>
              <% if invitation.event.photo.attached? %>
                <%= cl_image_tag invitation.event.photo.key, width: 125, height: 125, crop: :fill, radius: 8 %>
              <% else %>
              <% end %>
            </div>
            <div class="text-event">
              <div class="table-event-name pl-2">
                <h5 class="event-title mt-3"><%= invitation.event.title %></h5>
                <p class="event-date"><%= invitation.event.start_date.strftime("%d" + "." + "%m" + "." +"%Y") %></p>
              </div>
              <div>
                <%= link_to event_path(invitation.event) do %>
                  <i class="fa-solid fa-eye icone-event"></i>
                <% end %>
              </div>
            </div>
          </td>
          <td class="text-center">
            <% if invitation.event.invitations.present? %>
              <%= invitation.event.invitations.length %>
            <% else %>
              <%= "-" %>
            <% end %>
          </td>
          <td class="text-center">
            <% if DateTime.now >= invitation.event.start_date %>

              <%= "Passé" %>
            <% else %>
              <%= "A venir" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>